CREATE TABLE VendingMachineState(Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT, CatalogState TEXT, AcceptedCoinsTypesNames TEXT);
CREATE TABLE StoreState(Id INTEGER PRIMARY KEY AUTOINCREMENT);
CREATE TABLE CashRegisterState(Id INTEGER PRIMARY KEY AUTOINCREMENT);
CREATE TABLE ControlPanelState(Id INTEGER PRIMARY KEY AUTOINCREMENT, InsertedCoinsTypesNames TEXT);